# 테스트 카테고리 및 상품 세팅
### - 대분류 카테고리 생성
POST http://localhost:8080/v1/categories
content-type:application/json

{
  "categoryName": "test1",
  "categoryLevel": 1
}

### - 중분류 카테고리 생성
POST localhost:8080/v1/categories
content-type:application/json

{
  "parentCategoryId": 1,
  "categoryName": "child category1",
  "categoryLevel": 2
}

### - 소분류 카테고리 생성
POST localhost:8080/v1/categories
content-type:application/json

{
  "parentCategoryId": 2,
  "categoryName": "child category1",
  "categoryLevel": 3
}

### 3. 할인 저장
POST localhost:8080/v1/discounts
content-type: application/json
X-MEMBER-ID: asdf
ROLE: ADMIN

{
  "discountName": "test discount 1",
  "discountType": "할인율",
  "discountValue": 20,
  "discountStartDate": "2025-02-22T00:00:00.000Z",
  "discountEndDate": "2025-02-23T00:00:00.000Z",
  "applyType": 2,
  "ids": [3]
}

### 4. 할인 조회
GET localhost:8080/v1/discounts

### - 제품 등록
POST http://localhost:8080/v1/products
Content-Type: application/json
X-MEMBER-ID: test
ROLE: ADMIN

{
  "name": "Product Name1",
  "description": "description.",
  "categoryId": 3,
  "price": 15000,
  "summaryDescription": "summary description.",
  "simpleDescription": "simple description.",
  "productOptions": [
    {
      "productOptionName": "option1",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "black"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "M"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 3333
    },
    {
      "productOptionName": "option2",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "white"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "M"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 3333
    },
    {
      "productOptionName": "option3",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "brown"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "M"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 3333
    }
  ],
  "thumbnail": "/thm/path",
  "productImages": {
    "paths": [
      "/path/1",
      "/path/2",
      "/path/3"
    ]
  },
  "tags": [
    {
      "tagName": "진짜 멋진거"
    }
  ]
}

### 5. (할인 포함) 제품 등록
POST http://localhost:8080/v1/products
Content-Type: application/json
X-MEMBER-ID: test
ROLE: ADMIN

{
  "name": "Product Name2",
  "description": "description.",
  "categoryId": 1,
  "price": 139900,
  "discountId": 1,
  "summaryDescription": "할인 포함된 제품입니다.",
  "simpleDescription": "할인 포함",
  "productOptions": [
    {
      "productOptionName": "black/L",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "black"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 0
    },
    {
      "productOptionName": "black/M",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "black"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "M"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 0
    },
    {
      "productOptionName": "white/L",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "white"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 1000
    }
  ],
  "thumbnail": "/thm/path",
  "productImages": {
    "paths": [
      "/path/1",
      "/path/2",
      "/path/3"
    ]
  },
  "tags": [
    {
      "tagName": "진짜 멋진거"
    },
    {
      "tagName": "진짜 chill한거"
    }
  ]
}


### 장바구니에 상품 추가
POST http://localhost:8080/v1/members/cart
Content-Type: application/json
X-MEMBER-ID: jle

[
  {
    "productOptionId": 1,
    "quantity": 1
  },
  {
    "productOptionId": 2,
    "quantity": 2
  },
  {
    "productOptionId": 3,
    "quantity": 2
  }
]

### 장바구니 상품 삭제
POST http://localhost:8080/v1/members/cart/delete
Content-Type: application/json
X-MEMBER-ID: jle

[
  {
    "cartItemId": 1
  },
  {
    "cartItemId": 2
  },
  {
    "cartItemId": 3
  }
]

### 장바구니에 상품 추가
POST http://localhost:8080/v1/members/cart
Content-Type: application/json
X-MEMBER-ID: jle

[
  {
    "productOptionId": 1,
    "quantity": 1
  },
  {
    "productOptionId": 2,
    "quantity": 2
  }
]

### 장바구니 옵션 변경
POST http://localhost:8080/v1/members/cart/option-update
Content-Type: application/json
X-MEMBER-ID: jle

[
  {
    "cartItemId": 4,
    "productOptionId": 3,
    "quantity": 4
  }
]

### 장바구니 조회
GET http://localhost:8080/v1/members/cart
X-MEMBER-ID: jle
