### 쿠폰생성(코드자동생성)
POST http://localhost:8080/v1/coupons
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "couponName": "무신사랑해50%쿠폰",
  "couponType": "RATE",
  "amount": 50,
  "minOrderPrice": 50000 ,
  "maxDiscountPrice": 1000,
  "couponStartDate": "2025-04-02",
  "couponEndDate": "2028-04-05",
  "issueType": "AUTO",
  "issueTargetType": "ALL",
  "applyType": "ALL_PRODUCTS",
  "couponIssueCode": "",
  "comment": ""
}

### 쿠폰생성(자동발급 + 특정회원)
POST http://localhost:8080/v1/coupons
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "couponName": "특정회원 10% 쿠폰",
  "couponType": "RATE",
  "amount": 10,
  "minOrderPrice": 0,
  "maxDiscountPrice": 0,
  "couponStartDate": "2025-04-02",
  "couponEndDate": "2026-04-05",
  "issueType": "AUTO",
  "issueTargetType": "MEMBERS",
  "issueTargetMemberIds": ["member1", "member2"],
  "applyType": "CATEGORY",
  "applyTargetIds": [1, 2],
  "comment": ""
}

### 쿠폰생성(코드직접입력)
POST http://localhost:8080/v1/coupons
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "couponName": "무신사랑해 5000원 쿠폰",
  "couponType": "FIXED",
  "amount": 5000,
  "minOrderPrice": 0 ,
  "maxDiscountPrice": 0,
  "couponStartDate": "2025-05-02",
  "couponEndDate": "2025-05-05",
  "issueType": "CODE",
  "issueTargetType": "ALL",
  "applyType": "PRODUCT",
  "applyTargetIds": [1001, 1002],
  "couponIssueCode": "TESTCOUPON",
  "comment": ""
}

### 쿠폰검색
POST http://localhost:8080/v1/coupons/search
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "couponName": null,
  "couponStartDate": null,
  "couponEndDate": null
}

### 쿠폰검색(이름으로 조회)
POST http://localhost:8080/v1/coupons/search
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "couponName": "50%",
  "couponStartDate": null,
  "couponEndDate": null
}

### 쿠폰검색(기간 조회)
POST http://localhost:8080/v1/coupons/search
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "couponName": null,
  "couponStartDate": "2025-05-01",
  "couponEndDate": "2025-05-07"
}

### 쿠폰 삭제
POST http://localhost:8080/v1/coupons/delete
Content-Type: application/json
X-MEMBER-ID: test@test.com
ROLE: ADMIN

{
  "couponId": 2
}

### 쿠폰발급
POST http://localhost:8080/v1/coupons/issue
X-MEMBER-ID: jle
Content-Type: application/json

{
  "couponIssueCode": "TESTCOUPON"
}

### 보유 쿠폰 조회
GET http://localhost:8080/v1/members/me/coupons
X-MEMBER-ID: jle
