### GET members
GET http://localhost:8080/v1/members

### GET member
GET http://localhost:8080/v1/members/me
X-USER-ID: test@test.com

### 회원가입
POST  http://localhost:8080/v1/members
Content-Type: application/json

{
  "memberId": "test@test.com",
  "password": "test",
  "name": "test-user",
  "birthday": "2025-05-06",
  "phoneNumber": "010-2244-5555",
  "gender": "F",
  "tosAgreement": true,
  "privacyAgreement": true,
  "marketingAgreement": true
}

### 회원정보 수정
POST  http://localhost:8080/v1/members/me/update
Content-Type: application/json
X-USER-ID: test@test.com

{
  "name": "test-user",
  "birthday": "2025-04-06",
  "phoneNumber": "010-1111-2222",
  "gender": "F",
  "tosAgreement": true,
  "privacyAgreement": true,
  "marketingAgreement": true
}

### 비밀번호 수정
POST  http://localhost:8080/v1/members/me/update/auth
Content-Type: application/json
X-USER-ID: test@test.com

{
  "oldPassword": "test",
  "newPassword": "1234"
}


### 회원탈퇴
POST  http://localhost:8080/v1/members/me/withdraw
Content-Type: application/json
X-USER-ID: test@test.com

{
  "memo":"사용하지 않음"
}