### 1. 카테고리 생성 (상품은 반드시 카테고리가 있어야 등록 가능)
POST http://localhost:8080/v1/categories
content-type:application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "categoryName": "test1",
  "categoryLevel": 1
}

### 1-1. 하위 카테고리 생성
POST localhost:8080/v1/categories
content-type:application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "parentCategoryId": 1,
  "categoryName": "child category1",
  "categoryLevel": 2
}

### 2. 제품 등록 ({옵션-상품옵션 테이블 자동등록}, {태그-기존태그 존재시 only 상품태그 저장, 기존태그 부재시 태그 테이블 & 상품 태그 테이블 저장}, {썸네일-자동 등록})
POST http://localhost:8080/v1/products
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "name": "니트1",
  "description": "description.",
  "categoryId": 1,
  "price": 15000,
  "summaryDescription": "summary description.",
  "simpleDescription": "simple description.",
  "productOptions": [
    {
      "productOptionName": "PON",
      "productOptionDetails": [
        {
          "productOptionType": "POT",
          "productOptionDetailName": "OPDN"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 3333
    }
  ],
  "thumbnail": "/thm/path",
  "productImages": {
    "paths": [
      "/path/1",
      "/path/2",
      "/path/3"
    ]
  },
  "tags": [
    {
      "tagName": "진짜 멋진거"
    }
  ]
}

### 3. 할인 저장
POST localhost:8080/v1/discounts
content-type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "discountName": "test discount 1",
  "discountType": "할인율",
  "discountValue": 20,
  "discountStartDate": "2025-07-01T00:00:00.000Z",
  "discountEndDate": "2025-07-29T00:00:00.000Z",
  "applyType": 2,
  "ids": [3]
}

### 4. 할인 조회
GET localhost:8080/v1/discounts


### 5. (할인 포함) 제품 등록
POST http://localhost:8080/v1/products
Content-Type: application/json
X-MEMBER-ID: jle
ROLE: ADMIN

{
  "name": "바지1",
  "description": "description.",
  "categoryId": 1,
  "price": 139900,
  "discountId": 1,
  "summaryDescription": "할인 포함된 제품입니다.",
  "simpleDescription": "할인 포함",
  "productOptions": [
    {
      "productOptionName": "black/L",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "black"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 0
    },
    {
      "productOptionName": "black/M",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "black"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "M"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 0
    },
    {
      "productOptionName": "white/L",
      "productOptionDetails": [
        {
          "productOptionType": "color",
          "productOptionDetailName": "white"
        },
        {
          "productOptionType": "size",
          "productOptionDetailName": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 1000
    }
  ],
  "thumbnail": "/thm/path",
  "productImages": {
    "paths": [
      "/path/1",
      "/path/2",
      "/path/3"
    ]
  },
  "tags": [
    {
      "tagName": "진짜 멋진거"
    },
    {
      "tagName": "진짜 chill한거"
    }
  ]
}

### 6. 회원 등록
POST  http://localhost:8080/v1/members
Content-Type: application/json

{
  "memberId": "test@test.com",
  "password": "test",
  "name": "test-user",
  "birthday": "2025-05-06",
  "phoneNumber": "010-2244-5555",
  "gender": "F",
  "tosAgreement": true,
  "privacyAgreement": true,
  "marketingAgreement": true
}


### 7. 주문 저장
POST http://localhost:8080/v1/orders
Content-Type: application/json
X-MEMBER-ID: test@test.com

{
  "addressInfo": {
    "address1": "서울특별시 강남구 테헤란로 123",
    "address2": "101동 202호",
    "postalCode": "06233",
    "receiver": "홍길동",
    "phoneNumber": "01012345678",
    "email": "hong@test.com"
  },
  "items": [
    {
      "productId": 1,
      "productOptionId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "productOptionId": 2,
      "quantity": 1
    }
  ],
  "paymentMethod": "CARD",
  "orderDetail": {
    "originalTotal": 176566,
    "discountedTotal": 27980,
    "productDiscount": 27980,
    "additionalDiscount": 0,
    "shippingFee": 0,
    "finalAmount": 148586
  }
}


### 8. 사용자 주문내역 조회
POST http://localhost:8080/v1/orders/search
Content-Type: application/json
X-MEMBER-ID: test@test.com

{
  "conditions": {
    "type": "ALL",
    "status": null,
    "startDate": "2025-01-01",
    "endDate": "2025-07-12"
  },
  "pageable": {
    "page": 0,
    "size": 10,
    "sort": {
      "direction": "desc",
      "properties": ["orderDate"]
    }
  }
}