### 카테고리 생성
POST localhost:8090/v1/category
content-type:application/json

{
}

### 제품 생성
POST localhost:8080/v1/product
content-type: application/json
X-MEMBER-ID: asdf
ROLE: ADMIN

{
  "name": "product1",
  "description": "product 1 description",
  "categoryId": 1,
  "productState": "NEW",
  "createdAt": "2025-02-12T11:17:32.355Z",
  "price": 1000,
  "discountId": 2,
  "summaryDescription": "abc",
  "simpleDescription": "abc",
  "isDeleted": false,
  "isSelling": true,
  "productOptions": [
    {
      "productOptionName": "black/L",
      "productOptionDetails": [
        {
          "optionType": "color",
          "optionValue": "black"
        },
        {
          "optionType": "size",
          "optionValue": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 0
    },
    {
      "productOptionName": "black/M",
      "productOptionDetails": [
        {
          "optionType": "color",
          "optionValue": "black"
        },
        {
          "optionType": "size",
          "optionValue": "M"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 0
    },
    {
      "productOptionName": "white/L",
      "productOptionDetails": [
        {
          "optionType": "color",
          "optionValue": "white"
        },
        {
          "optionType": "size",
          "optionValue": "L"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 1000
    }
  ]
}

### 단일 제품 조회
GET localhost:8080/v1/product/2
X-MEMBER-ID: asdf


### 제품 수정
POST localhost:8080/v1/product/update-product
content-type: application/json
X-MEMBER-ID: asdf
ROLE: ADMIN

{
  "id": 1,
  "name": "updated product1",
  "description": "product 1 description",
  "categoryId": 1,
  "productState": "NEW",
  "createdAt": "2025-02-12T11:17:32.355Z",
  "price": 1000,
  "discountId": 1,
  "summaryDescription": "string",
  "simpleDescription": "string",
  "isDeleted": false,
  "isSelling": true
}


### 전체 제품 조회 (페이지네이션)
GET http://localhost:8080/v1/product?page=1&size=3
X-MEMBER-ID: asdf

### 할인 추가
POST http://localhost:8080/v1/discounts
Content-Type: application/json
X-MEMBER-ID: asdf
ROLE: ADMIN

{
  "discountName": "test discount 2",
  "discountType": "할인율",
  "discountValue": 20,
  "discountStartDate": "2025-02-22T00:00:00.000Z",
  "discountEndDate": "2025-02-23T00:00:00.000Z"
}



### GET category list
GET http://152.67.211.72:18080/product/v1/categories

### POST category
POST http://localhost:8080/v1/categories
Content-Type: application/json

{
  "categoryName": "test1",
  "categoryLevel": 1
}

### POST category
POST http://localhost:8090/v1/categories
Content-Type: application/json

{
  "categoryName": "test2",
  "categoryLevel": 2
}

### POST category
POST http://localhost:8090/v1/categories
Content-Type: application/json

{
  "categoryName": "test3",
  "categoryLevel": 3
}

### GET category
GET http://localhost:8090/v1/categories/1

### POST category with parent
POST http://localhost:8090/v1/categories
Content-Type: application/json

{
  "parentCategoryId": 2,
  "categoryName": "test4",
  "categoryLevel": 3
}

### POST category(부모 id 에러 테스트)
POST http://localhost:8090/v1/categories
Content-Type: application/json

{
  "parentCategoryId": 1000,
  "categoryName": "test5",
  "categoryLevel": 2
}

### POST category(레벨 범위 벗어나는 요청 테스트)
POST http://localhost:8090/v1/categories
Content-Type: application/json

{
  "categoryName": "test6",
  "categoryLevel": 4
}

### GET category
GET http://localhost:8090/v1/categories/4

### GET category (존재하지 않는 id 조회 테스트)
GET http://localhost:8090/v1/categories/444

### UPDATE category
POST http://localhost:8090/v1/categories/update-category
Content-Type: application/json

{
  "categoryId": 1,
  "categoryName": "update1"
}

### UPDATE category name 에러 테스트
POST http://localhost:8090/v1/categories/update-category
Content-Type: application/json

{
  "categoryId": 1,
  "categoryName": ""
}

### UPDATE category
POST http://localhost:8090/v1/categories/update-category
Content-Type: application/json

{
  "categoryId": 1,
  "categoryLevel": 3
}

### UPDATE category level 에러 테스트
POST http://localhost:8090/v1/categories/update-category
Content-Type: application/json

{
  "categoryId": 1,
  "categoryLevel": 4
}

### DELETE category
POST http://localhost:8090/v1/categories/delete-category
Content-Type: application/json

{
  "categoryId": 4
}