### Category
POST http://localhost:8080/v1/categories
Content-Type: application/json

{
  "categoryName" : "test2",
  "categoryLevel" : 1
}

### Save Product - Thumbnails Test
POST http://localhost:8080/v1/product
Content-Type: application/json
X-USER-ID: test
ROLE: ADMIN

{
  "name": "Product Name2",
  "description": "description.",
  "categoryId": 1,
  "price": 22222,
  "summaryDescription": "summary description.",
  "simpleDescription": "simple description.",
  "productOptions": [
    {
      "productOptionName": "PON",
      "productOptionDetails": [
        {
          "productOptionType": "POT",
          "productOptionDetailName": "OPDN"
        }
      ],
      "stockQuantity": 10,
      "additionalPrice": 3333
    }
  ],
  "thumbnails": {
    "paths": [
      "/path/1",
      "/path/2",
      "/path/3"
    ]
  }

}

### 확인 - 상품 조회
GET http://localhost:8080/v1/product

